### ISSUE TITLE
Implement more intelligent inventory handling

### ISSUE THREAD

**Issue by miabbott** [aweiteka/UATFramework#15]
I discussed the issues we have with using dynamic and static inventory with @whitel

Langdon smartly pointed out we have the same data in 3 global variables and that is **A Bad Thing**.

I suggested we scrap our existing inventory mess and switch to a more simple version of:

``` gherkin
Given "{hosts}" from an inventory
```

And then **remote_cmd()** would try to get an Ansible inventory dynamically and fallback to a static inventory.

This should clean things up and even enable a feature file to switch between a dynamic and static inventory per step (assuming you want to act like a crazy person).

The downside is that basically all our feature files would have to be re-written...

I think this is possible, thoughts?

**Comment by aweiteka** [comment]
I don't see it quite the same way.
1. These are really used as a booleans in most cases
2. These are properties of an object rather than global vars
3. It's a way to have more focused, readable feature files that don't have to do housekeeping along the way. It's DRY

However, surgery is much easier now than later.

**Comment by miabbott** [comment]
Here's an alternate proposal:

In order to reduce confusion between static/dynamic inventory, we scrap the static inventory support in its current form.

Right now, the static inventory support is looking for a Ansible inventory file in INI format.  However, the same can be achieved by passing in a **resources.json** file with one or more hosts defined, to the dynamic inventory code path.  (Honestly, I added in support for the INI file because I didn't fully understand how the dynamic inventory worked.)

Langdon's last PR included a sample **resouces.json** file that can be used as the blueprint for anyone who would like to test outside of the CI environment.

----- Original Message -----

**Comment by langdon** [comment]
@aweiteka sure, technically not a global var, but shares the characteristic of making it unclear to a consumer where to get the "host"  param for remote_cmd. 

Personally, I am "6 of one" on it. I just think we need a clear way to allow a user to 1) pick up the target host from the feature file or 2) override the target host where necessary. 

Is that what you are proposing in #14?

Otherwise, I agree with @miabbott and think we should just use dynamic host but with a static resources.json

**Comment by miabbott** [comment]
Continued the discussion with @aweiteka this afternoon.

Latest idea is to keep the ability to choose dynamic/static inventory via feature file.

The change would be to set a new variable `context.inventory` to either **dynamic** or **static**

Additionally, we would set `context.target_host` during the steps where dynamic/static inventory is decided.

Then in **environment.py**, we can check to see if the `context.inventory` variable is set to one or another.  We will default to static.

Additionally, the code for `remote_cmd()` would default to `host=None`, allow for **host** to be set during the call to the method, but use `context.target_host` otherwise.

Thoughts?  Comments?

**Comment by aweiteka** [comment]
@miabbott make it so!

**Comment by aweiteka** [comment]
@miabbott this was fixed by PR#15, correct?

**Comment by miabbott** [comment]
Yes, I believe it was.
